INFO:root:Command line executed: python /nfsd/VFdisk/ivancichst/thesis/TAT-code/TAT/main.py --dataset CollegeMsg --model TAT --gpu 0
INFO:root:----------------------------------------
INFO:root:Full args parsed:
INFO:root:root_dir=/nfsd/VFdisk/ivancichst/thesis/TAT-code/TAT
INFO:root:checkpoint_dir=/nfsd/VFdisk/ivancichst/thesis/TAT-code/TAT/checkpoint/
INFO:root:datadir=/nfsd/VFdisk/ivancichst/thesis/TAT-code/TAT/data/
INFO:root:dataset=CollegeMsg
INFO:root:force_cache=False
INFO:root:directed=False
INFO:root:gpu=0
INFO:root:set_indice_length=3
INFO:root:seed=0
INFO:root:data_usage=0.6
INFO:root:test_ratio=0.2
INFO:root:parallel=False
INFO:root:model=TAT
INFO:root:layers=2
INFO:root:hidden_features=128
INFO:root:dropout=0.1
INFO:root:negative_slope=0.2
INFO:root:use_attention=True
INFO:root:epoch=50
INFO:root:batch_size=8
INFO:root:lr=0.0005
INFO:root:l2=0.001
INFO:root:optimizer=adam
INFO:root:metric=acc
INFO:root:perm_loss=0.1
INFO:root:in_features=9
INFO:root:out_features=6
INFO:root:prop_depth=1
INFO:root:max_sp=4
INFO:root:sp_feature_type=sp
INFO:root:time_encoder_type=tat
INFO:root:time_encoder_maxt=3000000.0
INFO:root:time_encoder_rows=1000000
INFO:root:time_encoder_dimension=64
INFO:root:time_encoder_discrete=uniform
INFO:root:time_encoder_deltas=0.5
INFO:root:log_dir=/nfsd/VFdisk/ivancichst/thesis/TAT-code/TAT/log/
INFO:root:save_log=False
INFO:root:debug=False
INFO:root:desc=description_string
INFO:root:time_str=2022_10_09_18_46_33
INFO:root:----------------------------------------
/usr/local/lib/python3.7/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py:106: UserWarning: 
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
train:   0%|          | 0/429 [00:00<?, ?it/s]train:   0%|          | 0/429 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nfsd/VFdisk/ivancichst/thesis/TAT-code/TAT/main.py", line 115, in <module>
    main()
  File "/nfsd/VFdisk/ivancichst/thesis/TAT-code/TAT/main.py", line 112, in main
    results = train_model(mod, dataloaders, args, logger)
  File "/nfsd/VFdisk/ivancichst/thesis/TAT-code/TAT/train.py", line 52, in train_model
    optimize_model(model, target_model, train_loader, optimizer, logger, summary_writer, step, perm_loss=args.perm_loss)
  File "/nfsd/VFdisk/ivancichst/thesis/TAT-code/TAT/train.py", line 359, in optimize_model
    prediction = model(batch)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nfsd/VFdisk/ivancichst/thesis/TAT-code/TAT/model.py", line 325, in forward
    x = layer(x=x, edge_index=edge_index, timestamps=timestamps)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nfsd/VFdisk/ivancichst/thesis/TAT-code/TAT/model.py", line 400, in forward
    out = self.propagate(edge_index, x=(x_l, x_r))
  File "/usr/local/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 367, in propagate
    size, kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 260, in __collect__
    data = self.__lift__(data, edge_index, dim)
  File "/usr/local/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 230, in __lift__
    return src.index_select(self.node_dim, index)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
srun: error: gpu2: task 0: Exited with exit code 1
